name: CMake Windows Build

on: [push]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'recursive'
      
      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
            vcpkgArguments: 'lua zlib rapidjson boost-beast boost-asio openssl websocketpp curl'
            vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
            vcpkgGitCommitId: '8dddc6c899ce6fdbeab38b525a31e7f23cb2d5bb'
            vcpkgTriplet: 'x64-windows-static'

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build-windows

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build-windows
        env:
          beammp_sentry_url: ${{ secrets.BEAMMP_SECRET_SENTRY_URL }}
        run: cmake $GITHUB_WORKSPACE -DSENTRY_BACKEND=breakpad -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE='${{ runner.workspace }}/b/vcpkg/scripts/buildsystems/vcpkg.cmake' -DVCPKG_TARGET_TRIPLET=x64-windows-static -DBEAMMP_SECRET_SENTRY_URL="$beammp_sentry_url"

      - name: Build
        working-directory: ${{github.workspace}}/build-windows
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BeamMP-Server.exe
          path: ${{github.workspace}}/build-windows/RelWithDebInfo/BeamMP-Server.exe
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BeamMP-Server.pdb
          path: ${{github.workspace}}/build-windows/RelWithDebInfo/BeamMP-Server.pdb


